### ISSUE TITLE
Bottom Bar container missing

### ISSUE THREAD

**Issue by adtm** [pansinm/react-chrome-tabs#3]
Thanks for the library! 
Just noticed that the bottom half is not going directly with the white background because the 
```html
<div class="chrome-tabs-bottom-bar"></div>
```
is missing comparing the forked version and the existing React fork.

**Comment by adtm** [comment]
https://github.com/pansinm/react-chrome-tabs/pull/4

**Comment by pansinm** [comment]
thks, i'll test and release later
