### ISSUE TITLE
Add a "new tab" button to the right of tabs

### ISSUE THREAD

**Issue by QuentinPhrl** [pansinm/react-chrome-tabs#5]
Hello

I'd like to know if it's currently possible to add the button to add a new tab on the right of the tabs as on Chrome? 

See more generally adding the possibility of adding one or more buttons with icons. 

Thank you for this superb library

**Comment by pansinm** [comment]
Now custom components are supported on the right side of the tab. https://codesandbox.io/embed/eager-galois-hq8uxb?fontsize=14&hidenavigation=1&theme=dark

**Comment by QuentinPhrl** [comment]
Thank you very much for this update. 
I'd also like to suggest that you add the possibility of making a tab non-deletable by the user, and hide the remove button of course.

**Comment by pansinm** [comment]
The tab supports using the `isCloseIconVisible` property to control whether the close icon is displayed.
