### ISSUE TITLE
Not working on Remix SPA

### ISSUE THREAD

**Issue by ozgurozalp** [pansinm/react-chrome-tabs#6]
It throws an error saying "window is not defined"

**Comment by pansinm** [comment]
The 2.4.5 version added a window undefined check, but it is uncertain whether it is effective.

**Comment by ozgurozalp** [comment]
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/e03bc510-d9aa-42ba-bd3f-e6d590fd9125">
I still get the error, the cause seems to be draggabilly.js :/

**Comment by pansinm** [comment]
I can’t modify the draggabilly.js.
I checked the Remix issue, and it seems like we can disable SSR. 

https://github.com/remix-run/remix/discussions/1023
https://github.com/ashikmeerankutty/client-test/pull/1/files

Not sure if it’s helpful.

**Comment by ozgurozalp** [comment]
SSR is already disabled in spa mode and the window thing is really annoying

**Comment by pansinm** [comment]
![图片](https://github.com/user-attachments/assets/7d0d77d1-e89d-4b3e-8887-b83fca4e33ab)

I gave it a try, and it works with dynamic imports.
