### ISSUE TITLE
Bad behaviour on pinnedRight

### ISSUE THREAD

**Issue by QuentinPhrl** [pansinm/react-chrome-tabs#7]
Hello,

I've just seen that the new pinnedRight props behave badly when you drag and drop menus from right to left. It should not be able to go beyond the pinnedRight component.

<img width="535" alt="Capture d’écran 2024-11-04 à 01 38 26" src="https://github.com/user-attachments/assets/5fdf4b2a-0717-4fe3-b5aa-658f06284081">

Another thing I've noticed is that there's no limit to drag and drop, and that it can go beyond the container on the right and left.

<img width="535" alt="Capture d’écran 2024-11-04 à 01 40 27" src="https://github.com/user-attachments/assets/374961ae-2a38-460a-9064-49b31d431bc8">

Thanks for your work

**Comment by pansinm** [comment]
Just released 2.4.5, trying to fix this issue. You can give it a try.

**Comment by QuentinPhrl** [comment]
Superb improvement, but there's a drag that doesn't seem necessary and that goes looking for a border that can cause the tab to go under the button. 
In my case this isn't a problem but I think that if it can be fixed it's not a bad thing.

<img width="536" alt="Capture d’écran 2024-11-06 à 16 53 24" src="https://github.com/user-attachments/assets/1cb24479-2c86-445c-ade5-4dac7450c59a">

Thanks again for making these fixes
